'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const norm=s=>String(s).normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-96)).replace(/[\uFE0E\uFE0F]/g,'');
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('emoji-'+key))??fallback}catch{return fallback}};
let saved=read('favorites',[]),recent=read('history',[]);
const state={tab:'all',category:'',mode:read('mode','compare'),favorites:new Set(Array.isArray(saved)?saved:[]),history:Array.isArray(recent)?recent:[],limit:120,results:[],detail:null};
if(!['native','google','compare'].includes(state.mode))state.mode='compare';
const byId=new Map(EMOJI.map(e=>[e.id,e]));
const aliases=[['植物 しょくぶつ','💐🌸💮🪷🏵️🌹🥀🌺🌻🌼🌷🪻🌱🪴🌲🌳🌴🌵🌾🌿☘️🍀🍁🍂🍃🪾🎍🎋🎄'],['木 樹木 じゅもく','🌲🌳🌴🪾🎄'],['重機 じゅうき 建設機械 けんせつきかい','🚜🏗️🚧'],['了解 りょうかい OK おっけー 承知 賛成 いいね','👍👌🙆🆗✅'],['ありがとう 感謝 お礼 ありがと','🙏🙇💐😊'],['お疲れ おつかれ 休憩 ひとやすみ','☕🍵👏🛀😌'],['暑い あつい 猛暑 夏','🥵☀️🔥🌞🫠'],['寒い さむい 冬','🥶❄️☃️🧣'],['嬉しい うれしい 喜び やった','😊😄😆🥰🙌🎉'],['困った こまった 困る 悩む どうしよう','😕😟😥🤦😰'],['お祝い おめでとう 祝福 誕生日','🎉🎊🎂🥂💐🎁'],['ごめん 謝る すみません 申し訳','🙇🙏😔'],['よろしく お願い 頼む','🙏🙇🤝'],['おはよう 朝 起きる','🌅☀️😊'],['おやすみ 眠い ねむい 寝る','😴💤🌙🛌'],['悲しい かなしい 泣く 涙','😢😭😞💔'],['怒る 怒り むかつく','😠😡🤬💢'],['びっくり 驚く すごい','😮😲🤯😳'],['がんばれ 頑張れ 応援 ファイト','💪📣👏🔥'],['またね さようなら バイバイ','👋🙋'],['おいしい 美味しい うまい','😋🤤🍽️'],['好き すき 愛 かわいい','❤️💕🥰😍🫶'],['考える なるほど 疑問','🤔💡🧐❓'],['ゴルフ ごるふ','⛳🏌️'],['電車 でんしゃ 列車','🚃🚆🚇🚄🚅'],['パソコン ぱそこん コンピュータ PC','💻🖥️⌨️🖱️'],['スマホ すまほ 携帯','📱📲'],['検索 さがす 探す','🔍🔎'],['注意 危険 警告','⚠️🚨❗'],['秘密 ひみつ 内緒','🤫🔒🤐'],['お金 おかね 支払い','💰💴💵💳'],['乾杯 かんぱい','🍻🥂🍺'],['疲れた つかれた','😩😫🥱😮‍💨'],['笑う 笑い わらう','😂🤣😆😁'],['雨 あめ','🌧️☔☂️'],['風邪 かぜ 病気 体調','🤧🤒😷'],['楽しい たのしい','😄🥳🎶'],['車 くるま ドライブ','🚗🚙🚘'],['旅行 りょこう お出かけ','🧳✈️🚄🗺️']];
let associations={},variantLookup=new Map();
function buildVariantLookup(variants={}){variantLookup=new Map();for(const [base,list] of Object.entries(variants)){const words=[base,...(Array.isArray(list)?list:[])],expanded=[...new Set(words.map(norm))];for(const w of expanded)variantLookup.set(w,expanded)}}
function variantsOf(word){return variantLookup.get(norm(word))||[norm(word)]}
function buildSearchIndex(){for(const e of EMOJI){const original=[e.name,e.en,...e.keywords,e.char];const related=[];for(const word of [e.name,...e.keywords]){for(const form of variantsOf(word))related.push(form);const list=associations[word]||associations[norm(word)];if(Array.isArray(list))for(const r of list)related.push(...variantsOf(r))}e.direct=norm(original.join(' '));e.assoc=norm([...new Set(related)].join(' '));e.alias=norm(aliases.filter(a=>a[1].includes(e.char)||a[1].replaceAll('\uFE0F','').includes(e.char.replaceAll('\uFE0F',''))).map(a=>a[0]).join(' '));}}
buildSearchIndex();
async function loadSearchDictionaries(){try{const [a,v]=await Promise.all([fetch('./associations.json').then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('./variants.json').then(r=>{if(!r.ok)throw Error();return r.json()})]);associations=a||{};buildVariantLookup(v||{});buildSearchIndex();render()}catch{associations={};buildVariantLookup({});buildSearchIndex();}}
function persist(k,v){try{localStorage.setItem('emoji-'+k,JSON.stringify(v))}catch{toast('保存できません。このブラウザの設定をご確認ください');}}
let toastTimer;function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1900)}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function google(e,large=false){if(e.x===null||e.x===undefined)return el('span','missing','画像なし');const n=el('span','googleemoji'+(large?' large':''));n.style.backgroundPosition=`${e.x*100/(SHEET.cols-1)}% ${e.y*100/(SHEET.rows-1)}%`;n.setAttribute('role','img');n.setAttribute('aria-label','Google系の'+e.name);return n}
function native(e){return el('span','emoji',e.char)}
function favorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);persist('favorites',[...state.favorites]);render(false);if(state.detail===id)openDetail(id,false)}
async function copy(e){let ok=false;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(e.char);ok=true}}catch{}if(!ok){const t=el('textarea');t.value=e.char;t.style.cssText='position:fixed;top:0;left:0;opacity:0.01;width:1px;height:1px';(document.querySelector('dialog[open]')||document.body).append(t);t.focus();t.select();t.setSelectionRange(0,t.value.length);try{ok=document.execCommand('copy')}catch{}t.remove()}
if(!ok){$('#manualText').value=e.char;$('#manualDialog').showModal();$('#manualText').select();return false}
state.history=[e.id,...state.history.filter(id=>id!==e.id)].slice(0,100);persist('history',state.history);toast('コピーしました '+e.char);if(state.tab==='history')render(false);return true}
function card(e){const c=el('article','card'),b=el('button','copy');b.setAttribute('aria-label',e.name+'をコピー');const v=el('span','visuals');if(state.mode!=='google')v.append(native(e));if(state.mode==='compare')v.append(el('span','divider'));if(state.mode!=='native')v.append(google(e));b.append(v,el('span','label',e.name));b.onclick=()=>copy(e);const tools=el('div','cardtools'),f=el('button',state.favorites.has(e.id)?'favorited':'',state.favorites.has(e.id)?'★':'☆');f.setAttribute('aria-label',e.name+'のお気に入りを切り替え');f.setAttribute('aria-pressed',state.favorites.has(e.id));f.onclick=()=>favorite(e.id);const d=el('button','',e.variants?.length?'… '+(e.variants.length+1):'…');d.setAttribute('aria-label',e.name+'の関連候補と詳細');d.onclick=()=>openDetail(e.id);tools.append(f,d);c.append(b,tools);return c}
function filter(){const terms=norm($('#query').value.trim()).split(/\s+/).filter(Boolean),color=$('#color').value,shape=$('#shape').value;let rows=EMOJI.filter(e=>!e.parent||state.favorites.has(e.id)&&state.tab==='favorites'||state.history.includes(e.id)&&state.tab==='history'||terms.some(t=>t===norm(e.char)));
if(state.tab==='favorites')rows=rows.filter(e=>state.favorites.has(e.id));if(state.tab==='history')rows=state.history.map(id=>byId.get(id)).filter(Boolean);
rows=rows.filter(e=>(!state.category||e.group===state.category)&&(!color||e.colors.includes(color))&&(!shape||e.shapes.includes(shape))&&terms.every(t=>e.direct.includes(t)||e.assoc.includes(t)||e.alias.includes(t)));
if(terms.length)rows.sort((a,b)=>score(b,terms)-score(a,terms));return rows}
function score(e,terms){return terms.reduce((v,t)=>v+(norm(e.char)===t?100:norm(e.name)===t?80:norm(e.name).includes(t)?40:e.direct.includes(t)?20:e.assoc.includes(t)?12:5),0)}
function render(reset=true){$('#app').dataset.mode=state.mode;const scroll=$('#scroll').scrollTop;if(reset){state.limit=120;$('#scroll').scrollTop=0}state.results=filter();const grid=$('#grid');grid.replaceChildren(...state.results.slice(0,state.limit).map(card));$('#count').textContent=state.results.length.toLocaleString()+'件';$('#more').hidden=state.results.length<=state.limit;$('#empty').hidden=!!state.results.length;if(!state.results.length){const msg=state.tab==='favorites'&&!state.favorites.size?'☆をタップすると、ここに保存されます。':state.tab==='history'&&!state.history.length?'コピーした絵文字が、ここに並びます。':'条件に合う絵文字がありません。別の言葉や分類でお試しください。';$('#empty').replaceChildren(el('p','',msg));if($('#query').value||state.category||$('#color').value||$('#shape').value){const b=el('button','','検索条件を解除');b.onclick=clearAll;$('#empty').append(b)}}
$$('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===state.mode);b.setAttribute('aria-pressed',b.dataset.mode===state.mode)});$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===state.tab);b.setAttribute('aria-pressed',b.dataset.tab===state.tab)});$$('[data-category]').forEach(b=>{b.classList.toggle('active',b.dataset.category===state.category);b.setAttribute('aria-pressed',b.dataset.category===state.category)});$('#comparehint').hidden=state.mode!=='compare';$('#clear').hidden=!$('#query').value;$('#filterToggle').textContent=($('#color').value||$('#shape').value)?'絞り込み ●':'絞り込み';if(!reset)$('#scroll').scrollTop=scroll;}
function clearAll(){$('#query').value='';$('#color').value='';$('#shape').value='';state.category='';render()}
function showDialog(d){if(!d.open)d.showModal()}
function openDetail(id,show=true){const e=byId.get(id);if(!e)return;state.detail=id;$('#detailTitle').textContent=e.name;const body=$('#detailBody');body.replaceChildren();const compare=el('div','detailcompare');for(const type of ['native','google']){const box=el('div');box.append(type==='native'?native(e):google(e,true),el('small','',type==='native'?'この端末':'Google系'));compare.append(box)}body.append(compare);const copybutton=el('button','primary','コピー '+e.char);copybutton.onclick=()=>copy(e);body.append(copybutton);const actions=el('div','detailactions'),fav=el('button','',state.favorites.has(id)?'★ お気に入り登録済み':'☆ お気に入りに登録');fav.onclick=()=>favorite(id);actions.append(fav);body.append(actions);
const root=byId.get(e.parent)||e,variantIds=[root.id,...(root.variants||[])];if(variantIds.length>1){body.append(el('h3','subheading','バリエーション · タップで拡大'));const group=el('div','variants');for(const vid of variantIds){const ve=byId.get(vid);const b=el('button','',ve.char);b.title=ve.name;b.setAttribute('aria-label',ve.name+'を大きく表示');b.setAttribute('aria-pressed',vid===id);b.onclick=()=>openDetail(vid);group.append(b)}body.append(group)}
body.append(el('h3','subheading','関連する絵文字'));const related=EMOJI.filter(x=>x.id!==root.id&&!x.parent&&x.subgroup===e.subgroup).map(x=>({e:x,s:x.keywords.filter(k=>e.keywords.includes(k)).length+(x.alias&&e.alias&&x.alias===e.alias?3:0)})).sort((a,b)=>b.s-a.s).slice(0,18);const grid=el('div','grid');grid.append(...related.map(x=>card(x.e)));body.append(grid);if(show){showDialog($('#detail'));body.scrollTop=0}}
for(const [name,id] of [['すべて',''],...GROUPS.map(x=>[x.name,x.id])]){const b=el('button','',name);b.dataset.category=id;b.onclick=()=>{state.category=id;render()};$('#categories').append(b)}
for(const color of ['赤','橙','黄','緑','青','紫','桃','茶','黒','白']){const o=el('option','',color);o.value=color;$('#color').append(o)}
$('#query').oninput=()=>render();$('#clear').onclick=()=>{$('#query').value='';render();$('#query').focus()};$('#color').onchange=$('#shape').onchange=()=>render();$('#resetFilters').onclick=()=>{$('#color').value='';$('#shape').value='';render()};$('#filterToggle').onclick=()=>{const hidden=!$('#filters').hidden;$('#filters').hidden=hidden;$('#filterToggle').setAttribute('aria-expanded',!hidden)};
$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;persist('mode',state.mode);render(false)});$$('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;clearAll()});$('#more').onclick=()=>{state.limit+=120;render(false)};$('#help').onclick=()=>showDialog($('#helpDialog'));$$('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',ev=>{const r=d.getBoundingClientRect();if(ev.target===d&&(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom))d.close()}));
// Short panels respond gently to a boundary drag without moving fixed controls.
for(const scroller of [$('#scroll'),...$$('.dialogbody')]){let start=null,drag=false;scroller.addEventListener('touchstart',e=>{start=e.touches.length===1?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null;drag=false},{passive:true});scroller.addEventListener('touchmove',e=>{if(!start)return;const dy=e.touches[0].clientY-start.y,dx=e.touches[0].clientX-start.x;if(Math.abs(dx)>Math.abs(dy))return;const edge=(scroller.scrollTop<=0&&dy>0)||(scroller.scrollTop+scroller.clientHeight>=scroller.scrollHeight-1&&dy<0);if(edge&&Math.abs(dy)>8){if(e.cancelable)e.preventDefault();drag=true;scroller.style.transform=`translateY(${Math.sign(dy)*Math.min(28,Math.abs(dy)*.16)}px)`}},{passive:false});const end=()=>{if(drag){scroller.style.transition='transform .22s ease-out';scroller.style.transform='';setTimeout(()=>scroller.style.transition='',230)}start=null};scroller.addEventListener('touchend',end);scroller.addEventListener('touchcancel',end)}
render();loadSearchDictionaries();
if('serviceWorker'in navigator&&location.protocol!=='file:'){navigator.serviceWorker.register('./sw.js').then(async reg=>{await navigator.serviceWorker.ready;$('#offlineStatus').textContent='オフライン準備完了。次回から通信がなくても検索・比較できます。'}).catch(()=>{$('#offlineStatus').textContent='オフライン保存は利用できません。オンラインでお使いください。'})}else $('#offlineStatus').textContent='オフライン対応にはHTTPSでの利用が必要です。';
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'search_emoji',title:'絵文字を検索',description:'日本語・英語・絵文字で検索し、表示中の検索結果を更新します。コピーは行いません。',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||typeof input.query!=='string'||input.query.length>100)throw Error('検索語は100文字以内で指定してください');state.tab='all';clearAll();$('#query').value=input.query;render();return {count:state.results.length,results:state.results.slice(0,20).map(e=>({emoji:e.char,name:e.name}))}}})).catch(()=>{})}catch{}}
